version: "3"
services:
  questions-service:
    build: ./
    environment: 
        DB_CONNECTION_URL: mongodb://mongo:27017
        APPLICATION_PORT: 443
    ports:
      - "443:443"
    depends_on: 
      - mongo
  mongo:
    image: mongo
    ports: 
      - "27017:27017"
